### PR TITLE
Added Discord to MC Attachments, Placeholders, and Mentions.

### PR DESCRIPTION
**Pull request by Mohron**
I guess I deleted my old PR when I was trying to sort out my branches. 

This PR includes some minor improvement on the attachment code as well as includes the support for additional placeholders in the `minecraft` template and readable mentions. I cannot find anyway to retrieve nicknames with Javacord so those are still not supported through mentions or placeholders.

@nguyenquyhy The attachment handling has to be made part of the `formatUrl` or a similar method to still support the hover and link properties as I can't set those with Vanilla formatting and just allow your method to handle the conversion to `Text` as I have done with everything else in this commit.

[Old PR](https://github.com/nguyenquyhy/Sponge-Discord/pull/22)

[Javacord Issue](https://github.com/BtoBastian/Javacord/issues/32)

### CODE REVIEW

**Comment by VankkaGithub** [comment]
Now i'm wondering if there is a way to detect if a user has a role that would be awesome ;)

**Comment by Mohron** [comment]
@VankkaGithub that's included in this PR.

**Comment by VankkaGithub** [comment]
hmm i tried this had no luck: http://pastebin.com/f1ruC0P2

**Comment by VankkaGithub** [comment]
nvm i had no luck with it being == but contains works fine

**Comment by VankkaGithub** [comment]
no actually still not having luck :/

**Comment by Mohron** [comment]
@VankkaGithub what are you trying to accomplish?

**Comment by nguyenquyhy** [comment]
I already added support for nickname 😄 .

**Comment by Mohron** [comment]
@nguyenquyhy I'm really interested in how!

**Comment by nguyenquyhy** [comment]
Check those out https://github.com/nguyenquyhy/Javacord/commit/513060efea084c16326f38543c528eb6a08589f2
https://github.com/nguyenquyhy/Sponge-Discord/commit/3df12705a2616622550222903b3a15ef8fbdc411

**Comment by Mohron** [comment]
@nguyenquyhy I knew I wasn't crazy!

**Comment by nguyenquyhy** [comment]
Can you help to resolve the conflict first 😋

**Comment by Mohron** [comment]
@nguyenquyhy I'll merge and utilize your new API feature as soon as I get off work. This is exciting stuff! :+1:

**Comment by Mohron** [comment]
@nguyenquyhy all good to go. Mentions, nicknames, roles etc are all working beautifully!

**Comment by nguyenquyhy** [comment]
@Mohron what is the role and role blacklist for?

**Comment by nguyenquyhy** [comment]
@Mohron May I know why you reverted my change of useNickname feature?

**Comment by Mohron** [comment]
@nguyenquyhy The role/role blacklist allows you to include the discord user's role in the minecraft template and blacklist roles that you don't want to be used. There's also a default role to set the name/color of user without a role or with only blacklisted roles.

I changed the nickname feature you pushed because I had already added all the functionality for nicknames into my feature set. The only thing I was waiting on was support from the Discord API which you added. You're free to implement features as you see fit of course but I was trying to keep the nickname support consistent with the rest of the features I added.

I tried to explain all my additions in my update to the readme. If you look under `minecraft` _> `chatTemplate` You will see there's now a list of placeholders instead of just %a & %s.  So instead of having a bollean to toggle %a to nicknames, %n can be used allowing greater flexibility.

**Comment by Mohron** [comment]
### EXAMPLE

`chatTemplate": "&8<&0[&r%c%r&0]&r %c%n&8> &7%s",`

chat

**Comment by nguyenquyhy** [comment]
I see it now. I am reorganizing the setting a bit. On the placeholder, I will remove %c and %n and make it default with flag to turn off. Having all those is flexible but I don't want to make it look too complex though.

**Comment by Mohron** [comment]
@nguyenquyhy %c is there so you can use the color from a role on other text as I do in my example.

**Comment by Mohron** [comment]
I was going to automatically include the color with the role but I didn't want to make that forced either.

**Comment by nguyenquyhy** [comment]
I will think about that a bit more. Maybe I'll changed my mind pretty quickly. 😋 

My main concern is I want to cater 2 groups of users: people who just started using the plugins, and people who are familiar with the plugin and have Minecraft & Discord servers with complex roles.

For 2nd groups, I want to have role-based templates, which actually make both %r and %c unnecessary in this case. The current `minecraft` > `chatTemplate` would be considered template for default role, making `defaultRole` setting also unnecessary.

With that in mind, I then want to make the rest as simple as possible to help the 1st group getting started.

I think I will need a couple of days to play around with different configuration to have a clearer idea.

Besides, I think %a and %n is actually a better implementation, but I think I will change that a bit: make %a to be either nickname or username and add something like %u for only username. This is to make sure people with default template aware of the new nickname support. 😄

**Comment by Mohron** [comment]
@nguyenquyhy I know this plugin is a side project for you and I'd really like to see it become as powerful as discordSRV is for Bukkit/spigot. I have plans for more improvements but I'd like to avoid wasting either of our time. I would like to try to get the implementations of our needs synced up with your vision where possible so everyone can benefit from my additions. If you get the time, maybe we can develop a plan so my edits won't conflict with yours in the future. I don't know if you actually use discord but I'm almost always available through discord.

**Comment by Mohron** [comment]
Also I think %n and %u definitely makes more sense but I didn't want to break older configs. I will try to just avoid the discord to minecraft side of the plugin until you make your changes.

**Comment by nguyenquyhy** [comment]
Really appreciate all your work on this plugin. Honestly I did not expect much contribution, so I was kinda lazy on writing down plan.

My suggestion is that we first collaborate on 2 config files: 1 is the default config, which should feature important features of the mods and do not scare people away due to complexity 😋; 2 is a full-blown config, featuring everything the plugin should be able to do.

Some more things I have in mind for the 2 config files:
- Everything in the 1st file should still be meaningful in the 2nd file. In other words, 2nd file = 1st file + add-on.
- 2nd file can have features that is not possible with current Sponge or Javacord.

I don't mind adding any features that does not affect config files, so I guess there won't be much conflicting work on those.

What do you think? 

I have Discord too. You can find me (Hy) on my server https://discord.gg/8gjs89d or Pixelmon's Discord server. I work weekdays (Singapore time) so I might not be very responsive at those time.

**Pull request merged**
