### PR TITLE
Added Discord to Minecraft attachment support

### PR DESCRIPTION
**Pull request by Mohron**
I've added a config and the capability for links to attachments in discord to appear in-game. Two things you might want to look at is the color of "[Attachment]" and the workaround I used for the lambda expression. I couldn't really find if there was another option to using an additional text variable since formattedMessage had to be final/effectively final.

### CODE REVIEW

**Comment by Mohron** [comment]
I'm working on making this more customizable with the config but I'm trying to avoid separating out the styling to it's own option. Let me know if you have any thoughts/ideas.

**Comment by nguyenquyhy** [comment]
How about "attachmentTemplate": "&6[Attachment]" in Minecraft section of the config?

**Comment by Mohron** [comment]
I've added that already but the issue is the Text objects in sponge don't directly support the color codes

**Comment by VankkaGithub** [comment]
`Text messageText = TextUtil.formatUrl(String.format(channelConfig.minecraft.chatTemplate.replace("%a", author), content));
                if (config.linkDiscordAttachments && message.getAttachments() != null) {
                    for (MessageAttachment attachment:message.getAttachments()) {
                        if(config.attachmentColor.startsWith("&3")){
                          messageText = Text.join(messageText,
                                Text.builder(" [Attachment]")
                                .color(TextColors.DARK_AQUA)
                                .onClick(TextActions.openUrl(attachment.getUrl()))
                                .onHover(TextActions.showText(Text.of("Click to open attachment.")))
                                .build());
                    }
                }
                        }
                Text formattedMessage = messageText;
`

something like this?

**Comment by Mohron** [comment]
@VankkaGithub See that requires a separate config option which I could do in a heartbeat (the code is already finished) but I want to just read it from the template (&X type format code(s)). And maybe I'm making a bigger deal out of it being separate than is needed lol.

Also are you planning more edits to the plugin yourself?

**Comment by Mohron** [comment]
I went ahead and made the color its own config so you can hopefully get this in. I was stumped as far as having the color built in to the `attachmentTemplate` unless it was only going to support on color code at the very beginning. I think the limitation is more easily understood by separating the color from the template. Feel free to improve upon it!

**Comment by VankkaGithub** [comment]
@Mohron yes i'm currently working on setting the game of the bot i don't think there is much to improve anyway :)

**Comment by VankkaGithub** [comment]
but it could be just the color code with no & of couse :)

**Comment by VankkaGithub** [comment]
also ofc i want my name to be just Vankka, Vankka2 cuz Vankka was allredy taken :P

**Comment by nguyenquyhy** [comment]
Since you can use & in template, I don't see why we would need a new `attachmentColor`. I guess only `attachmentTemplate` and `attachmentHoverTemplate` are good enough. If you are not sure how to make & work in the template, I can help you to add that 😄 .

I will release 2.2.0 and will merge this for 2.3.0.

**Comment by VankkaGithub** [comment]
sience people would try do [&2Attachemnt&r] and stuff like that

**Comment by Mohron** [comment]
> since people would try do [&attachment&r] and stuff like that
@nguyenquyhy This is what I'm trying to avoid. I don't know how we can support multiple colors and still use the hover property over the entire template. Either way if you have a cleaver work around I'd love to see/learn from it because it would be useful for my upcoming PRs.

**Comment by nguyenquyhy** [comment]
As far as I remember from Sponge API, hover is not affected by color formatting. 
Also I still don't understand why you would try to avoid `[&2attachment&r]`. Can you explain a bit more? Is that because of troubling making hovering work? 😄 
Allowing colors in template would also allow people to have rainbow if they want: `[&2a&3t&4t&5a&6c&7h...`.

**Comment by Mohron** [comment]
@nguyenquyhy The issue is how you add color to Sponge's text, not supporting multiple colors. Via the Text API, you use the builder to add colors and it's separated from the text. Then you can add an action like the on hover at the same time you designate the color (one color). You must know something I don't know because the Text API doesn't seem super friendly when it comes to supporting multiple colors/format as each time you change, you need a new Text object.

https://docs.spongepowered.org/master/en-GB/plugin/text/text.html

**Comment by VankkaGithub** [comment]
:/ there is a conflict

**Comment by Mohron** [comment]
@VankkaGithub Your PR was added that's why ha ha.

**Comment by nguyenquyhy** [comment]
I can still merge, don't worry.

@Mohron Yes they are not very friendly, but we already have a function to do very similar thing: https://github.com/nguyenquyhy/Sponge-Discord/blob/master/src/main/java/com/nguyenquyhy/discordbridge/utils/TextUtil.java#L70. 😃

**Comment by Mohron** [comment]
@nguyenquyhy I'll leave you be with this one and get back to work on the mentions/nicks/roles from Discord to MC I was working on.

**Comment by VankkaGithub** [comment]
:) nice @Mohron

**Pull request closed without merging**
