### PR TITLE
2 Small things

### PR DESCRIPTION
**Pull request by Vankka2**
- Messages from bot user won't send in-game
- Adds config option for blacklisted prefix

### CODE REVIEW

**Comment by Vankka2** [comment]
Also a little config change of one line


  "botToken": "",
  **"prefixBlacklist": "",**
  "minecraftBroadcastTemplate": "",

**Comment by nguyenquyhy** [comment]
Can you make this "Messages from bot user won't send in-game" configurable?

The reason I used the special char instead of the bot ID is that I still want bot's messages to be able to forward to Minecraft except those from the plugin itself. For example, I have PixelBot to route messages between Pixelmon servers and Discord. At the same time, there is a separate Python engine that allows PixelBot to answer questions. So I want people from Minecraft to be able to ask a question, the question routes to Discord by Discord Bridge, the Python engine answers the question in Discord (also using PixelBot) and the answer is routed back to Minecraft by Discord Bridge.

I think a good way would be adding something like `"useSpecialChar": false`. If it is set to false (default), just use bot ID and ignore this `content.contains(TextUtil.SPECIAL_CHAR`, if it is set to true, do the reversed.

What do you think about that?

**Comment by nguyenquyhy** [comment]
Also, do you think prefixBlacklist should be a list? 😄 Is that overkill?

**Comment by Vankka2** [comment]
hmm propably can manage to do that but i'm not sure i know how to do the table thing as i just wanted to make a separate discord.js thing to work with the sane bit as the plugin so i can make a command for !players and have it not spam in game and someone wanted me to make a pr :D

**Comment by Vankka2** [comment]
oh crap... the files from my pc transfered

**Comment by Vankka2** [comment]
i don't know how to pr lol

**Comment by nguyenquyhy** [comment]
It is quite a lot of commit here, so I will squash it and merge. You might have to do a force pull and push from the though.
I will add change the blacklist into a list and clean unnecessary files :).

Many thanks for the new features! 👍

**Comment by Vankka2** [comment]
okay but i just added the config option for the bot message cancel thing xD

**Comment by Vankka2** [comment]
nvm all the things are in

**Comment by Vankka2** [comment]
pst you should look thru the commit as i intended this to just be my little fork so some things such as -vFork happend...

**Comment by nguyenquyhy** [comment]
Yep I have looked through every files 😄

**Pull request merged**
